// Code generated by mockery v2.2.1. DO NOT EDIT.

package mocks

import (
	environment "cloudpro-metadata-handler/service/environment"

	mock "github.com/stretchr/testify/mock"
)

// EnvironmentServiceInterface is an autogenerated mock type for the EnvironmentServiceInterface type
type EnvironmentServiceInterface struct {
	mock.Mock
}

// GetEnvVars provides a mock function with given fields:
func (_m *EnvironmentServiceInterface) GetEnvVars() *environment.EnvironmentVars {
	ret := _m.Called()

	var r0 *environment.EnvironmentVars
	if rf, ok := ret.Get(0).(func() *environment.EnvironmentVars); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*environment.EnvironmentVars)
		}
	}

	return r0
}
